API
JsonParser API::JP
vector<topology*> API::topologies
bool API::readJson(string fileName)
References JsonParser::read, JsonParser::store.
Referenced by testingAPI::testing_function1, testingAPI::testing_function2, testingAPI::testing_function3, testingAPI::testing_function4, testingAPI::testing_function5, testingAPI::testing_function6.
bool API::writeJson(string topologyID, string fileName)
References JsonParser::write.
Referenced by testingAPI::testing_function2.
vector< topology * > API::queryTopology()
Referenced by testingAPI::testing_function3, testingAPI::testing_function4, testingAPI::testing_function5, testingAPI::testing_function6.
bool API::deleteTopology(string TopologyID)
Referenced by testingAPI::testing_function4.
vector< component * > API::queryDevices(string topologyID)
Referenced by testingAPI::testing_function5.
vector< component * > API::queryDevicesWithNetlistNode(string topologyID, string NetlistNode)
Referenced by testingAPI::testing_function6.