topology
vector<component*> topology::components
string topology::id
void topology::setID(string ID)
Referenced by JsonParser::store.
string topology::getID()
Referenced by testingAPI::testing_function4, testingAPI::testing_function5, testingAPI::testing_function6, JsonParser::write.
component * topology::insertComponent(string &ID, string &TYPE, double &DEFAULT, double &MIN, double &MAX, map< string, string > &NETLIST)
Referenced by JsonParser::store.
vector< component * > topology::getComponents()
Referenced by testingAPI::testing_function5, testingAPI::testing_function6, JsonParser::write.
vector< component * > topology::getComponentsWithNetlistId(string Node)
bool topology::hasThatId(string ID)
topology::~topology()