JsonParser
json JsonParser::read(string fileName)
Referenced by API::readJson.
void JsonParser::store(json jsonData, topology *newTopology)
References topology::insertComponent, topology::setID.
Referenced by API::readJson.
void JsonParser::write(topology *targetTopology, string fileName)
References topology::getComponents, topology::getID.
Referenced by API::writeJson.