testingAPI
bool testingAPI::testing_function1()
References API::readJson.
Referenced by main.
bool testingAPI::testing_function2()
References API::readJson, API::writeJson.
Referenced by main.
bool testingAPI::testing_function3()
References API::queryTopology, API::readJson.
Referenced by main.
bool testingAPI::testing_function4()
References API::deleteTopology, topology::getID, API::queryTopology, API::readJson.
Referenced by main.
bool testingAPI::testing_function5()
References topology::getComponents, topology::getID, API::queryDevices, API::queryTopology, API::readJson.
Referenced by main.
bool testingAPI::testing_function6()
References topology::getComponents, topology::getID, API::queryDevicesWithNetlistNode, API::queryTopology, API::readJson.
Referenced by main.